# Generated by Django 5.1.7 on 2025-03-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_wholesale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(upload_to='wholesale_products/')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_products', to='products.wholesalecategory')),
            ],
        ),
    ]
